language: python
python:
  - "2.7"
install: 
  - sudo apt-get update -qq
  - sudo apt-get install -qq libfuse-dev cmake libc6-dev binutils
  - "pip install -r requirements.txt"
script: paver mk_appimage
