#!/bin/sh
# AppRun - Setup portable environment and invoke BitTorrent Sync GUI
#
die() {
    echo "$@"
    exit 1
}
find_in_path() {
    local IFS=:
    for sp in $PATH; do
        if [ -x "$sp/$1" ]; then 
            echo "$sp/$1"
            return 0
        fi
    done
    return 1
}
case "$0" in
    /*|./*|../*) 
        cd `dirname "$0"` > /dev/null || \
            die 'I cannot CD to where this script was run from,' \ 
                'So cannot invoke app. Sorry.';;
    *)
        #TODO find in path
esac

#TODO: set env and run
